Repository vshn/application-catalog-docs, pull requests merged in 2022-03, with the labels that each got.

#18 Remove old manage-service documentation
  docs/docs/antora.yml
  docs/docs/modules/ROOT/assets/images/emergency.png
  docs/docs/modules/ROOT/assets/images/vshn_logo.png
  docs/docs/modules/ROOT/examples/emergency.gv
  docs/docs/modules/ROOT/nav.adoc
  docs/docs/modules/ROOT/pages/.vale.ini
  docs/docs/modules/ROOT/pages/explanations/backup_concept.adoc
  docs/docs/modules/ROOT/pages/explanations/dns_cnames_root.adoc
  docs/docs/modules/ROOT/pages/explanations/lvm_snapshots_burp.adoc
  docs/docs/modules/ROOT/pages/explanations/mongodb_burp.adoc
  docs/docs/modules/ROOT/pages/explanations/monitoring_concept.adoc
  docs/docs/modules/ROOT/pages/explanations/postgresql_burp.adoc
  docs/docs/modules/ROOT/pages/explanations/s3_backup_restores.adoc
  docs/docs/modules/ROOT/pages/explanations/solr_backup_restore.adoc
  docs/docs/modules/ROOT/pages/explanations/vcs_repos_burp.adoc
  docs/docs/modules/ROOT/pages/how-tos/customer_pacco.adoc
  docs/docs/modules/ROOT/pages/how-tos/dns_serial_number_rollover.adoc
  docs/docs/modules/ROOT/pages/how-tos/list_available_backups.adoc
  docs/docs/modules/ROOT/pages/how-tos/list_files_backup.adoc
  docs/docs/modules/ROOT/pages/how-tos/restore_from_backup.adoc
  docs/docs/modules/ROOT/pages/how-tos/restore_mysql_burp.adoc
  docs/docs/modules/ROOT/pages/how-tos/view_backup_log_file.adoc
  docs/docs/modules/ROOT/pages/index.adoc
  docs/docs/modules/ROOT/partials/nav-explanation.adoc
  docs/docs/modules/ROOT/partials/nav-howtos.adoc
  docs/docs/modules/ROOT/partials/nav-reference.adoc
  docs/docs/modules/ROOT/partials/nav-tutorials.adoc
  docs/docs/modules/ROOT/partials/nav.adoc
Labels: change

#16 Add quality requirements for AppCat
  Guardfile
  docs/modules/ROOT/pages/reference/quality-requirements.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/maintainability/readiness-standards.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/portability/backup-exports.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/automatic-updates.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/backup-interval.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/mandatory-updates.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/actionable-alerts.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/api-declarative.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/api-validation.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/logs.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/provisioning-time.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#23 Fix links in quality requirements
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: bug

#19 Decision: Converged Service provisioning implementation
  docs/modules/ROOT/assets/images/appcat_proposal_1.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_2.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_3.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_4.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_5.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_7.drawio.svg
  docs/modules/ROOT/assets/images/appcat_proposal_8.drawio.svg
  docs/modules/ROOT/pages/explanations/decisions/converged-service-impl.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#25 Document MySQLGaleraClusterSmall
  docs/modules/ROOT/pages/runbooks/mariadbgalera/MySQLGaleraClusterSmall.adoc
  docs/modules/ROOT/partials/nav-runbooks.adoc
Labels: documentation

#29 Add glossary page
  docs/antora.yml
  docs/modules/ROOT/pages/.vale.ini
  docs/modules/ROOT/pages/explanations/decisions/converged-service-impl.adoc
  docs/modules/ROOT/pages/reference/glossary.adoc
  docs/modules/ROOT/pages/reference/quality-requirements.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/maintainability/readiness-standards.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/portability/backup-exports.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/automatic-updates.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/backup-interval.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/reliability/mandatory-updates.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/actionable-alerts.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/api-declarative.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/api-validation.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/logs.adoc
  docs/modules/ROOT/pages/reference/quality-requirements/usability/provisioning-time.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: change
