Repository vshn/application-catalog-docs, pull requests merged in 2022-12, with the labels that each got.

#43 Add missing navigation link for converged location
  docs/modules/ROOT/pages/explanations/decisions/converged-service-loc.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: bug, documentation

#44 Add addition about how to expose versions
  docs/modules/ROOT/pages/explanations/decisions/api-design.adoc
Labels: documentation, decision

#45 Update decision on AppCat deployment
  docs/modules/ROOT/assets/images/deployment3.drawio.svg
  docs/modules/ROOT/pages/explanations/decisions/composition-deployments.adoc
Labels: decision

#48 Add additional documentation for mariadb and redis debugging
  docs/modules/ROOT/pages/how-tos/mariadbgalera/debug.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: documentation

#49 Add missing document
  docs/modules/ROOT/pages/how-tos/redis/no_active_leader.adoc
Labels: bug

#50 Mariadb redis improved debug docs
  docs/modules/ROOT/pages/how-tos/redis/no_active_leader.adoc
Labels: bug
