Repository vshn/application-catalog-docs, pull requests merged in 2023-07, with the labels that each got.

#73 Maturity level metrics to reflect current technical capabilities
  docs/modules/ROOT/pages/reference/service-maturity.adoc
Labels: documentation

#74 Add generic metric handling document
  docs/modules/ROOT/pages/explanations/decisions/generic-metrics.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: change

#75 Add decision for Redis upgrade policy
  docs/modules/ROOT/pages/explanations/decisions/redis-upgrades.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: decision
