Repository vshn/application-catalog-docs, pull requests merged in 2024-12, with the labels that each got.

#122 Central Control Plane and Exoscale OSB API
  docs/modules/ROOT/assets/images/exoscale-marketplace-empty-service.png
  docs/modules/ROOT/assets/images/universal-control-plane.drawio.svg
  docs/modules/ROOT/pages/reference/arch-control-plane.adoc
  docs/modules/ROOT/pages/reference/exoscale-osbapi.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: enhancement

#125 Add docs about SLI Prober with split control plane
  docs/modules/ROOT/pages/reference/control-plane-pitfalls.adoc
  docs/modules/ROOT/pages/reference/sli-prober-architecture.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: change

#127 AppCat maturity level Backup extended with e2e tests
  docs/modules/ROOT/pages/reference/service-maturity.adoc
Labels: documentation
