Repository vshn/application-catalog-docs, pull requests merged in 2024-07, with the labels that each got.

#105 Update bootstrap_cluster.adoc
  docs/modules/ROOT/pages/how-tos/mariadbgalera/bootstrap_cluster.adoc
Labels: documentation

#107 Added HA alert rules docs
  docs/modules/ROOT/pages/how-tos/appcat/vshn/ha-alert-deployment.adoc
  docs/modules/ROOT/pages/how-tos/appcat/vshn/ha-alert-statefulset.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: change

#106 Add runbook for failed backups
  docs/modules/ROOT/pages/how-tos/appcat/AppCatBackupJobError.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: enhancement

#109 Add new appcat release process decision
  docs/modules/ROOT/pages/explanations/decisions/release_process.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: decision
