Repository vshn/application-catalog-docs, pull requests merged in 2025-02, with the labels that each got.

#136 Forgejo restore documentation
  docs/modules/ROOT/pages/service/forgejo-codey/restore.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#133 Add ADR for Function Revisions
  docs/modules/ROOT/pages/adr/0030-function-revisions.adoc
  docs/modules/ROOT/pages/adr/index.adoc
  docs/modules/ROOT/partials/nav-adrs.adoc
  templates/adr/cookiecutter.json
Labels: decision

#137 Add note about cloudbilling
  docs/modules/ROOT/pages/framework/cloud-usage-reporting.adoc
Labels: change
